services:
  - type: web
    name: multiplatform-admin
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
